keys:
  - &lewis_gpg 7369D9C25A365E6C926ADBAB48B34CF9C735A6AE
  - &user_age_key age1lzf4exwy6guezs2wqftd5hf5ftkcjmcvd7lyukvud66py9pk4aeqwx2p9h
  - &all_age_keys "age1dn3panz9kx6g6petqm8lyund72gslwt29p6grlq9cf5t3cd68gcqxlv289,age15q885zhzw0x5kk75upc30cql3nhkj7ugrxr0gs80tds988acgetszzd4px"

creation_rules:
  # System secrets - keep GPG for security
  - path_regex: secrets/secrets\.yaml$
    pgp: *lewis_gpg
    age: *all_age_keys
  # User secrets - prioritize age for convenience
  - path_regex: secrets/user\.yaml$
    age: *user_age_key
    pgp: *lewis_gpg
  # Other secrets
  - path_regex: secrets/.*\.yaml$
    pgp: *lewis_gpg
    age: *all_age_keys
  - path_regex: secrets/.*\.json$
    pgp: *lewis_gpg
    age: *all_age_keys
  - path_regex: hosts/.*/secrets\.yaml$
    pgp: *lewis_gpg
    age: *all_age_keys
