keys:
  - &lewis_gpg 7369D9C25A365E6C926ADBAB48B34CF9C735A6AE

creation_rules:
  - path_regex: secrets/.*\.yaml$
    pgp: *lewis_gpg
  - path_regex: secrets/.*\.json$
    pgp: *lewis_gpg
  - path_regex: hosts/.*/secrets\.yaml$
    pgp: *lewis_gpg
