#!/usr/bin/env bash
# Script: {{NAME}}
# Category: {{CATEGORY}}
# Description: {{DESCRIPTION}}
# Usage: ./{{NAME}} [OPTIONS]
# Author: Generated by new-script on {{DATE}}
# Integration: {{INTEGRATION}}
#
# {{DESCRIPTION}}
#
# This script provides [detailed description of functionality].
#
# Examples:
#   ./{{NAME}} --help
#   ./{{NAME}} --verbose
#   ./{{NAME}} --dry-run
#
# Exit codes:
#   0 - Success
#   1 - General error
#   2 - Invalid arguments
#
# Environment variables:
#   DEBUG - Enable debug output (default: 0)
#   VERBOSE - Enable verbose output (default: 0)
#
# Dependencies:
#   - bash 5.0+
#   - coreutils
#   - TODO: Add your dependencies here

set -euo pipefail

# ============================================================================
# Configuration
# ============================================================================

SCRIPT_NAME="{{NAME}}"
SCRIPT_VERSION="1.0.0"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default configuration
DEBUG="${DEBUG:-0}"
VERBOSE="${VERBOSE:-0}"
DRY_RUN=0

# ============================================================================
# Color Output
# ============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# ============================================================================
# Logging Functions
# ============================================================================

log_error() {
  echo -e "${RED}❌ ERROR:${NC} $*" >&2
}

log_warning() {
  echo -e "${YELLOW}⚠️  WARNING:${NC} $*" >&2
}

log_success() {
  echo -e "${GREEN}✅ SUCCESS:${NC} $*"
}

log_info() {
  echo -e "${BLUE}ℹ️  INFO:${NC} $*"
}

log_debug() {
  [[ "$DEBUG" == "1" ]] && echo -e "${CYAN}🔍 DEBUG:${NC} $*" >&2
}

log_verbose() {
  [[ "$VERBOSE" == "1" ]] && echo -e "${CYAN}💬 VERBOSE:${NC} $*"
}

# ============================================================================
# Helper Functions
# ============================================================================

# Check if command exists
command_exists() {
  command -v "$1" >/dev/null 2>&1
}

# Check if running as root
is_root() {
  [[ $EUID -eq 0 ]]
}

# Require root privileges
require_root() {
  if ! is_root; then
    log_error "This script requires root privileges"
    log_info "Please run with sudo: sudo $0 $*"
    exit 1
  fi
}

# Die with error message
die() {
  log_error "$*"
  exit 1
}

# ============================================================================
# Dependency Checks
# ============================================================================

check_dependencies() {
  local missing_deps=()

  # Add your required commands here
  local required_commands=(
    # "curl"
    # "jq"
    # "git"
  )

  for cmd in "${required_commands[@]}"; do
    if ! command_exists "$cmd"; then
      missing_deps+=("$cmd")
    fi
  done

  if [[ ${#missing_deps[@]} -gt 0 ]]; then
    log_error "Missing required dependencies:"
    for dep in "${missing_deps[@]}"; do
      echo "  - $dep" >&2
    done
    echo "" >&2
    log_info "Install missing dependencies:"
    echo "  nix-shell -p ${missing_deps[*]}" >&2
    exit 1
  fi
}

# ============================================================================
# Help & Usage
# ============================================================================

show_help() {
  cat << EOF
Usage: $SCRIPT_NAME [OPTIONS]

{{DESCRIPTION}}

Options:
  -h, --help              Show this help message
  -v, --verbose           Enable verbose output
  -d, --debug             Enable debug output
  -n, --dry-run           Show what would be done without doing it
  --version               Show version information

Examples:
  $SCRIPT_NAME --help
  $SCRIPT_NAME --verbose
  $SCRIPT_NAME --dry-run

Environment:
  DEBUG=1                 Enable debug output
  VERBOSE=1               Enable verbose output

Exit Codes:
  0                       Success
  1                       General error
  2                       Invalid arguments

For more information, see:
  scripts/{{CATEGORY}}/README.md
EOF
}

show_version() {
  echo "$SCRIPT_NAME version $SCRIPT_VERSION"
}

# ============================================================================
# Argument Parsing
# ============================================================================

parse_args() {
  while [[ $# -gt 0 ]]; do
    case $1 in
      -h|--help)
        show_help
        exit 0
        ;;
      -v|--verbose)
        VERBOSE=1
        shift
        ;;
      -d|--debug)
        DEBUG=1
        VERBOSE=1
        shift
        ;;
      -n|--dry-run)
        DRY_RUN=1
        log_info "Dry-run mode enabled (no changes will be made)"
        shift
        ;;
      --version)
        show_version
        exit 0
        ;;
      -*)
        log_error "Unknown option: $1"
        echo "" >&2
        show_help >&2
        exit 2
        ;;
      *)
        # Positional argument
        log_error "Unexpected argument: $1"
        echo "" >&2
        show_help >&2
        exit 2
        ;;
    esac
  done
}

# ============================================================================
# Main Logic
# ============================================================================

main() {
  log_debug "Script started: $SCRIPT_NAME"
  log_debug "Working directory: $SCRIPT_DIR"

  # Check dependencies
  check_dependencies

  # TODO: Add your main logic here
  log_info "This is a template script. Add your implementation here."

  # Example implementation structure:

  # Step 1: Validation
  log_verbose "Validating inputs..."

  # Step 2: Processing
  log_verbose "Processing..."

  if [[ "$DRY_RUN" == "1" ]]; then
    log_info "Would perform actions here (dry-run mode)"
  else
    log_verbose "Performing actions..."
    # Do actual work
  fi

  # Step 3: Completion
  log_success "Script completed successfully"

  log_debug "Script finished: $SCRIPT_NAME"
}

# ============================================================================
# Entry Point
# ============================================================================

# Parse command-line arguments
parse_args "$@"

# Run main logic
main

# Exit successfully
exit 0
