{
  config,
  inputs,
  lib,
  pkgs,
  themeContext ? null,
  ...
}:
let
  inherit (lib)
    hasAttr
    mkIf
    mkMerge
    mkOption
    optionalString
    types
    ;

  cfg = config.theming.signal or { };
  appsCfg = cfg.applications or { };
  appCfg = appsCfg.ironbar or { };
  configEnabled = appCfg.enable or false;
  ironbarEnabled = (cfg.enable or false) && configEnabled;

  theme = if themeContext != null && themeContext ? theme then themeContext.theme else null;

  colors = if theme != null && theme ? colors then theme.colors else null;

  spacing = {
    xs = "4px"; # 1x - Tight internal spacing
    sm = "8px"; # 2x - Module container padding
    md = "12px"; # 3x - Standard element padding
    lg = "16px"; # 4x - Wider element padding
    xl = "20px"; # 5x - Extra spacing
    xxl = "24px"; # 6x - Maximum spacing
  };

  radius = {
    sm = "8px"; # Small elements (buttons, chips)
    md = "12px"; # Module pills
  };

  defaultIronbarConfig = {
    monitors = {
      "DP-3" = {
        position = "top";
        height = 40;
        layer = "top";
        exclusive_zone = true;
        popup_gap = 8;
        popup_autohide = false;
        start_hidden = false;
        anchor_to_edges = false;
        icon_theme = "Papirus";
        margin = {
          top = 8;
          bottom = 0;
          left = 16;
          right = 16;
        };
        start = [
          {
            type = "workspaces";
            class = "workspaces";
            name_map = {
              "1" = "1";
              "2" = "2";
              "3" = "3";
              "4" = "4";
              "5" = "5";
            };
          }
          {
            type = "focused";
            class = "label";
            truncate = "end";
            length = 40;
          }
        ];
        center = [
          {
            type = "clock";
            class = "clock";
            format = "%H:%M";
            format_popup = "%A, %B %d, %Y";
          }
        ];
        end = [
          {
            type = "sys_info";
            class = "sys-info";
            format = [
              "  {cpu_percent}%"
              "  {memory_percent}%"
            ];
          }
          {
            type = "script";
            class = "brightness";
            mode = "poll";
            format = "󰃠 {}%";
            cmd = "brightnessctl -m | awk -F '[(),%]' '{print $6}'";
            interval = 1000;
            on_click_left = "brightnessctl set 10%-";
            on_click_right = "brightnessctl set +10%";
            tooltip = "Brightness: {}%";
          }
          {
            type = "volume";
            class = "volume";
            format = "{icon} {percentage}%";
            max_volume = 100;
            icons = {
              volume_high = " ";
              volume_medium = " ";
              volume_low = " ";
              muted = "󰝟 ";
            };
          }
          {
            type = "tray";
            class = "tray";
            icon_size = 16;
          }
          {
            type = "notifications";
            class = "notifications";
            icon_size = 16;
          }
        ];
      };
    };
  };

  hostSystem =
    if pkgs ? stdenv && pkgs.stdenv ? hostPlatform && pkgs.stdenv.hostPlatform ? system then
      pkgs.stdenv.hostPlatform.system
    else
      pkgs.stdenv.system;

  flakePackage =
    if inputs ? ironbar && inputs.ironbar ? packages && hasAttr hostSystem inputs.ironbar.packages then
      let
        systemPackages = inputs.ironbar.packages.${hostSystem};
      in
      systemPackages.default or (systemPackages.ironbar or null)
    else
      null;

  packageOverride = appCfg.package or null;

  resolvedPackage =
    if packageOverride != null then
      packageOverride
    else if flakePackage != null then
      flakePackage
    else
      pkgs.ironbar;

  extraCssText = appCfg.extraCss or "";

  baseCss =
    if colors == null then
      null
    else
      ''
        /* ============================================
           SIGNAL THEME COLORS
           ============================================ */
        @define-color surface_subtle ${colors."surface-subtle".hex};
        @define-color surface_base ${colors."surface-base".hex};
        @define-color surface_emphasis ${colors."surface-emphasis".hex};
        @define-color text_primary ${colors."text-primary".hex};
        @define-color text_secondary ${colors."text-secondary".hex};
        @define-color divider_primary ${colors."divider-primary".hex};
        @define-color accent_primary ${colors."accent-primary".hex};
        @define-color accent_focus ${colors."accent-focus".hex};
        @define-color accent_info ${colors."accent-info".hex};
        @define-color accent_danger ${colors."accent-danger".hex};

        /* ============================================
           IRONBAR GTK CSS STYLING
           Generated by Signal theme. Use `ironbar inspect`
           to explore nodes and iterate safely.
           ============================================ */

        * {
          font-family: "JetBrainsMono Nerd Font", "Iosevka Nerd Font", sans-serif;
          font-size: 14px;
          font-weight: 600;
          border: none;
          border-radius: 0;
          min-height: 0;
          box-shadow: none;
          text-shadow: none;
          outline-offset: 0;
          -gtk-icon-effect: none;
        }

        window#ironbar,
        #bar,
        .background {
          background-color: rgba(0, 0, 0, 0);
          background-image: none;
        }

        .workspaces,
        .label,
        .clock,
        .sys-info,
        .brightness,
        .volume,
        .tray {
          background-color: @surface_subtle;
          color: @text_primary;
          border-radius: ${radius.md};
          border: 1px solid @divider_primary;
          margin: ${spacing.xs};
          padding: ${spacing.xs} ${spacing.lg};
        }

        .workspaces {
          padding: ${spacing.xs} ${spacing.sm};
        }

        .workspaces button {
          background-color: transparent;
          color: @text_secondary;
          min-height: 24px;
          min-width: 28px;
          padding: ${spacing.xs} ${spacing.md};
          margin: 0 ${spacing.xs};
          border-radius: ${radius.sm};
        }

        .workspaces button.visible {
          background-color: @surface_subtle;
        }

        .workspaces button:hover:not(.focused) {
          background-color: @surface_emphasis;
          color: @text_primary;
        }

        .workspaces button.focused {
          background-color: @accent_focus;
          color: @surface_base;
        }

        .workspaces button:focus-visible {
          outline: 2px solid @accent_primary;
          outline-offset: 2px;
        }

        .clock {
          color: @text_secondary;
        }

        .sys-info {
          color: @accent_info;
        }

        .sys-info > * {
          background: none;
          border: none;
          margin: 0;
          padding: 0 ${spacing.sm};
        }

        .sys-info,
        .brightness,
        .volume,
        .notifications {
          font-size: 14px;
        }

        .brightness {
          color: @accent_info;
        }

        .volume {
          color: @accent_primary;
        }

        .tray {
          padding: ${spacing.xs} ${spacing.md};
        }

        .tray image {
          min-width: 16px;
          min-height: 16px;
        }

        revealer {
          margin: 0;
          padding: 0;
          min-height: 0;
        }

        widget.widget-container > revealer > overlay.notifications,
        .notifications {
          margin: 0;
          padding: 0;
          background: none;
          border: none;
          color: @text_secondary;
          min-height: 0;
        }

        overlay.notifications button.text-button {
          background-color: @surface_subtle;
          border-radius: ${radius.md};
          border: 1px solid @divider_primary;
          padding: 6px ${spacing.md};
          margin: ${spacing.xs};
          background-image: none;
          box-shadow: none;
          min-width: 16px;
          min-height: 16px;
        }

        overlay.notifications button.text-button label {
          padding: 0;
          margin: 0;
          min-height: 16px;
          min-width: 16px;
          font-size: 14px;
        }

        overlay.notifications button.text-button:active,
        overlay.notifications button.text-button:focus {
          padding: 6px ${spacing.md};
          margin: ${spacing.xs};
          border: 1px solid @divider_primary;
          box-shadow: none;
          outline: none;
        }

        .notifications image {
          min-width: 16px;
          min-height: 16px;
        }

        .notifications.notification-count {
          color: @accent_danger;
        }

        .label {
          color: @text_primary;
          font-style: italic;
          min-width: 0;
        }

        .label label {
          color: @text_primary;
        }

        .clock:hover,
        .label:hover,
        .notifications:hover,
        .notifications button:hover {
          background-color: @surface_emphasis;
          color: @text_primary;
        }

        tooltip {
          background-color: @surface_base;
          border: 1px solid @divider_primary;
          border-radius: ${radius.md};
          padding: ${spacing.sm} ${spacing.md};
        }

        popup {
          background-color: @surface_base;
          border: 1px solid @divider_primary;
          border-radius: ${radius.md};
          padding: ${spacing.md};
        }
      '';

  cssBody =
    if baseCss == null then
      null
    else
      baseCss + optionalString (extraCssText != "") ("\n" + extraCssText);
in
{
  options.theming.signal.applications.ironbar = {
    config = mkOption {
      type = types.attrs;
      default = defaultIronbarConfig;
      description = ''
        Ironbar configuration forwarded directly to `programs.ironbar.config`.
        The default ships with the Signal desktop layout (workspaces & title on the
        left, clock centered, status indicators on the right). Override this per-host
        to match the monitor names reported by your compositor.
      '';
    };

    package = mkOption {
      type = types.nullOr types.package;
      default = null;
      description = ''
        Optional override for the Ironbar package. When unset, the module uses the
        Ironbar flake input (matching upstream releases) and falls back to
        `pkgs.ironbar` if the flake is unavailable.
      '';
    };

    systemd = mkOption {
      type = types.bool;
      default = true;
      description = "Launch Ironbar as a user systemd service.";
    };

    features = mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = ''
        Compile-time Ironbar features to enable (for example "battery" or "lua").
        Passed through to `programs.ironbar.features`.
      '';
    };

    extraCss = mkOption {
      type = types.lines;
      default = "";
      description = ''
        Additional GTK4 CSS appended after the generated Signal stylesheet.
        Handy for rapid tweaks without forking the managed file.
      '';
    };
  };

  config = mkMerge [
    (mkIf configEnabled {
      programs.ironbar = {
        enable = true;
        package = resolvedPackage;
        inherit (appCfg) systemd features config;
      };
    })
    (mkIf (ironbarEnabled && cssBody != null) {
      xdg.configFile."ironbar/style.css" = {
        text = cssBody;
      };
    })
  ];
}
