# This file was generated by nvfetcher, please do not modify it manually.
# deadnix: skip-file
{
  fetchgit,
  # deadnix: ignore
  fetchurl,
  # deadnix: ignore
  fetchFromGitHub,
  # deadnix: ignore
  dockerTools,
}: {
  zsh-abbr = {
    pname = "zsh-abbr";
    version = "13b34cdc29d8b22323fa2079193ea1529723747c";
    src = fetchgit {
      url = "https://github.com/olets/zsh-abbr.git";
      rev = "13b34cdc29d8b22323fa2079193ea1529723747c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-F1IIvSzXDuneqE5tYJPP6JmiAFEGqZu5lFzevQLsRrQ=";
    };
    date = "2025-08-19";
  };
  zsh-auto-notify = {
    pname = "zsh-auto-notify";
    version = "b51c934d88868e56c1d55d0a2a36d559f21cb2ee";
    src = fetchgit {
      url = "https://github.com/MichaelAquilina/zsh-auto-notify.git";
      rev = "b51c934d88868e56c1d55d0a2a36d559f21cb2ee";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-s3TBAsXOpmiXMAQkbaS5de0t0hNC1EzUUb0ZG+p9keE=";
    };
    date = "2025-06-23";
  };
  zsh-autopair = {
    pname = "zsh-autopair";
    version = "449a7c3d095bc8f3d78cf37b9549f8bb4c383f3d";
    src = fetchgit {
      url = "https://github.com/hlissner/zsh-autopair.git";
      rev = "449a7c3d095bc8f3d78cf37b9549f8bb4c383f3d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-3zvOgIi+q7+sTXrT+r/4v98qjeiEL4Wh64rxBYnwJvQ=";
    };
    date = "2024-07-14";
  };
  zsh-bd = {
    pname = "zsh-bd";
    version = "646f06d9b6a840926a671fdc2da196d4eecfc305";
    src = fetchgit {
      url = "https://github.com/Tarrasch/zsh-bd.git";
      rev = "646f06d9b6a840926a671fdc2da196d4eecfc305";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-JAC9u7IzkW0b7J43w4c+yLuPGdvMtxBlobrQwlyvVcM=";
    };
    date = "2025-01-09";
  };
  zsh-defer = {
    pname = "zsh-defer";
    version = "53a26e287fbbe2dcebb3aa1801546c6de32416fa";
    src = fetchgit {
      url = "https://github.com/romkatv/zsh-defer.git";
      rev = "53a26e287fbbe2dcebb3aa1801546c6de32416fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-MFlvAnPCknSgkW3RFA8pfxMZZS/JbyF3aMsJj9uHHVU=";
    };
    date = "2024-02-10";
  };
  zsh-you-should-use = {
    pname = "zsh-you-should-use";
    version = "64dd9e3ff977e4ae7d024602b2d9a7a4f05fd8f6";
    src = fetchgit {
      url = "https://github.com/MichaelAquilina/zsh-you-should-use.git";
      rev = "64dd9e3ff977e4ae7d024602b2d9a7a4f05fd8f6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-u3abhv9ewq3m4QsnsxT017xdlPm3dYq5dqHNmQhhcpI=";
    };
    date = "2025-07-10";
  };
  zsh_codex = {
    pname = "zsh_codex";
    version = "6ede649f1260abc5ffe91ef050d00549281dc461";
    src = fetchgit {
      url = "https://github.com/tom-doerr/zsh_codex.git";
      rev = "6ede649f1260abc5ffe91ef050d00549281dc461";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-m3m+ErBakBMrBsoiYgI8AdJZwXgcpz4C9hIM5Q+6lO4=";
    };
    date = "2025-03-23";
  };
}
