# Per-system formatting with treefmt-nix
# Dendritic pattern: Provides nix fmt and checks.treefmt for each system
# Replaces standalone treefmt.toml and modules/per-system/formatters.nix
{ inputs, ... }:
{
  imports = [ inputs.treefmt-nix.flakeModule ];

  perSystem =
    { pkgs, ... }:
    {
      treefmt = {
        projectRootFile = "flake.nix";

        settings.global.excludes = [
          "secrets/*.yaml"
          "flake.lock"
          # Vendored third-party flakes: not ours to format, and prettier
          # hard-fails on some of their YAML, which reddens `nix fmt` wholesale.
          "vendor/*"
          # nvfetcher output, regenerated by `nix run .#update-all`. While the
          # source list is empty the fetcher arguments are unused, so deadnix
          # strips them — and nvfetcher writes them straight back, so the tree
          # can never settle. That standoff fails `nix flake check` on treefmt
          # with no edit of ours involved. The file's own header says not to
          # modify it manually; this makes the formatter honour that.
          "overlays/_sources/generated.nix"
        ];

        # Nix formatters
        programs.nixfmt.enable = true;
        programs.deadnix = {
          enable = true;
          no-lambda-arg = true;
        };

        # Shell formatter
        programs.shfmt = {
          enable = true;
          indent_size = 2;
        };

        # Statix linter/fixer with file excludes (migrated from statix.toml)
        programs.statix = {
          enable = true;
          includes = [ "*.nix" ];
          excludes = [
            "**/systems.nix"
          ];
        };

        # Prettier for YAML and Markdown
        settings.formatter.prettier-yaml = {
          command = "${pkgs.prettier}/bin/prettier";
          options = [ "--write" ];
          includes = [
            "*.yaml"
            "*.yml"
          ];
          excludes = [ "secrets/*.yaml" ];
        };

        settings.formatter.prettier-markdown = {
          command = "${pkgs.prettier}/bin/prettier";
          options = [
            "--write"
            "--prose-wrap"
            "always"
          ];
          includes = [ "*.md" ];
        };
      };
    };
}
