{
  programs.git-cliff = {
    enable = true;

    settings = {
      changelog = {
        header = ''
          # Changelog

          All notable changes to this project will be documented in this file.
        '';
        body = ''
          {% if version %}\
              ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
          {% else %}\
              ## [unreleased]
          {% endif %}\
          {% for group, commits in commits | group_by(attribute="group") %}
              ### {{ group | upper_first }}
              {% for commit in commits %}
                  - {% if commit.scope %}**{{commit.scope}}**: {% endif %}{{ commit.message | upper_first }}\
              {% endfor %}
          {% endfor %}

        '';
        footer = ''
          <!-- generated by git-cliff -->
        '';
        trim = true;
      };

      git = {
        conventional_commits = true;
        filter_unconventional = true;
        split_commits = false;
        commit_preprocessors = [
          # Remove issue numbers from commits
          {
            pattern = ''\((\w+\s)?#([0-9]+)\)'';
            replace = "";
          }
        ];
        commit_parsers = [
          {
            message = "^feat";
            group = "Features";
          }
          {
            message = "^fix";
            group = "Bug Fixes";
          }
          {
            message = "^doc";
            group = "Documentation";
          }
          {
            message = "^perf";
            group = "Performance Improvements";
          }
          {
            message = "^refactor";
            group = "Refactoring";
          }
          {
            message = "^style";
            group = "Code Style";
          }
          {
            message = "^test";
            group = "Tests";
          }
          {
            message = "^chore\\(release\\): prepare for";
            skip = true;
          }
          {
            message = "^chore\\(deps\\)";
            skip = true;
          }
          {
            message = "^chore\\(pr\\)";
            skip = true;
          }
          {
            message = "^chore\\(pull\\)";
            skip = true;
          }
          {
            message = "^chore";
            group = "Miscellaneous Chores";
          }
          {
            message = "^ci";
            group = "CI/CD";
          }
          {
            message = "^build";
            group = "Build System";
          }
          {
            message = "^revert";
            group = "Reverts";
          }
          {
            body = ".*security";
            group = "Security";
          }
        ];
        protect_breaking_commits = false;
        filter_commits = false;
        tag_pattern = "v[0-9].*";
        skip_tags = "v0.1.0-beta.1";
        ignore_tags = "";
        topo_order = false;
        sort_commits = "oldest";
      };
    };
  };
}
