name: "Build and Cache"

on:
  push:
    branches: [main]
    paths:
      - "**.nix"
      - "flake.lock"
      - ".github/workflows/cachix.yml"
  workflow_dispatch:  # Keep manual trigger option

# Cancel previous runs of this workflow when a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build and cache NixOS configuration
  build-and-cache-nixos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: ${{ secrets.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          pushFilter: "(-source$|nixpkgs-unstable-)"

      - name: Cleanup disk space before build
        run: |
          echo "📊 Disk space before cleanup:"
          df -h
          echo ""
          echo "🧹 Cleaning up Nix store and caches..."
          # Remove eval cache to free space (SQLite databases)
          rm -rf ~/.cache/nix/eval-cache-v* || true
          rm -rf ~/.cache/nix-shells/temp-* || true
          rm -rf ~/.cache/nix-builds/temp-* || true
          # Garbage collect Nix store
          nix-collect-garbage -d || true
          # Clean up any temporary result symlinks
          find . -name "result*" -type l -delete 2>/dev/null || true
          echo ""
          echo "📊 Disk space after cleanup:"
          df -h

      - name: Build NixOS configuration (jupiter)
        run: |
          nix build .#nixosConfigurations.jupiter.config.system.build.toplevel \
            --accept-flake-config \
            --print-build-logs \
            --fallback \
            --no-link

      - name: Push to Cachix
        if: success()
        run: |
          nix build .#nixosConfigurations.jupiter.config.system.build.toplevel --json \
            --accept-flake-config \
            --no-link \
            | jq -r '.[].outputs | to_entries[].value' \
            | cachix push ${{ secrets.CACHIX_CACHE_NAME }}

      - name: Cleanup after build
        if: always()
        run: |
          echo "📊 Disk space after build:"
          df -h
          echo ""
          echo "🧹 Final cleanup..."
          nix-collect-garbage -d || true
          rm -rf ~/.cache/nix/eval-cache-v* || true
          rm -rf result* || true
          echo ""
          echo "📊 Final disk space:"
          df -h

  # Build and cache Darwin configuration
  build-and-cache-darwin:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: ${{ secrets.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          pushFilter: "(-source$|nixpkgs-unstable-)"

      - name: Cleanup disk space before build
        run: |
          echo "📊 Disk space before cleanup:"
          df -h
          echo ""
          echo "🧹 Cleaning up Nix store and caches..."
          # Remove eval cache to free space (SQLite databases)
          rm -rf ~/.cache/nix/eval-cache-v* || true
          rm -rf ~/.cache/nix-shells/temp-* || true
          rm -rf ~/.cache/nix-builds/temp-* || true
          # Garbage collect Nix store
          nix-collect-garbage -d || true
          # Clean up any temporary result symlinks
          find . -name "result*" -type l -delete 2>/dev/null || true
          echo ""
          echo "📊 Disk space after cleanup:"
          df -h

      - name: Build Darwin configuration
        run: |
          nix build .#darwinConfigurations.Lewiss-MacBook-Pro.system \
            --accept-flake-config \
            --print-build-logs \
            --fallback \
            --no-link

      - name: Push to Cachix
        if: success()
        run: |
          nix build .#darwinConfigurations.Lewiss-MacBook-Pro.system --json \
            --accept-flake-config \
            --no-link \
            | jq -r '.[].outputs | to_entries[].value' \
            | cachix push ${{ secrets.CACHIX_CACHE_NAME }}

      - name: Cleanup after build
        if: always()
        run: |
          echo "📊 Disk space after build:"
          df -h
          echo ""
          echo "🧹 Final cleanup..."
          nix-collect-garbage -d || true
          rm -rf ~/.cache/nix/eval-cache-v* || true
          rm -rf result* || true
          echo ""
          echo "📊 Final disk space:"
          df -h

  # Cache development shells
  cache-dev-shells:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        shell:
          - default
          - node
          - python
          - rust
          - go
          - web
          - devops

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: ${{ secrets.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Cleanup disk space before build
        run: |
          echo "📊 Disk space before cleanup:"
          df -h
          echo ""
          echo "🧹 Cleaning up Nix store and caches..."
          # Remove eval cache to free space (SQLite databases)
          rm -rf ~/.cache/nix/eval-cache-v* || true
          rm -rf ~/.cache/nix-shells/temp-* || true
          rm -rf ~/.cache/nix-builds/temp-* || true
          # Garbage collect Nix store
          nix-collect-garbage -d || true
          # Clean up any temporary result symlinks
          find . -name "result*" -type l -delete 2>/dev/null || true
          echo ""
          echo "📊 Disk space after cleanup:"
          df -h

      - name: Build and cache dev shell (${{ matrix.shell }})
        run: |
          nix build .#devShells.x86_64-linux.${{ matrix.shell }} \
            --accept-flake-config \
            --print-build-logs \
            --fallback \
            --no-link \
            --json \
            | jq -r '.[].outputs | to_entries[].value' \
            | cachix push ${{ secrets.CACHIX_CACHE_NAME }}

      - name: Cleanup after build
        if: always()
        run: |
          echo "📊 Disk space after build:"
          df -h
          echo ""
          echo "🧹 Final cleanup..."
          nix-collect-garbage -d || true
          rm -rf ~/.cache/nix/eval-cache-v* || true
          rm -rf result* || true
          echo ""
          echo "📊 Final disk space:"
          df -h

  # Summary job
  cachix-success:
    runs-on: ubuntu-latest
    needs: [build-and-cache-nixos, build-and-cache-darwin, cache-dev-shells]
    if: always()

    steps:
      - name: Check build results
        run: |
          if [ "${{ needs.build-and-cache-nixos.result }}" == "failure" ] || \
             [ "${{ needs.build-and-cache-darwin.result }}" == "failure" ] || \
             [ "${{ needs.cache-dev-shells.result }}" == "failure" ]; then
            echo "❌ One or more cache jobs failed"
            exit 1
          fi
          echo "✅ All configurations cached successfully"
