name: NixOS Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v3

      - name: Run NixOS Test
        run: nix build --accept-flake-config --file tests/default.nix
