name: Test POG Scripts

on:
  push:
    paths:
      - 'pkgs/pog-scripts/**'
      - 'lib/output-builders.nix'
      - '.github/workflows/test-update-scripts.yml'
  pull_request:
    paths:
      - 'pkgs/pog-scripts/**'
  workflow_dispatch:

jobs:
  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Test update-all (dry-run)
        run: |
          nix run .#update-all -- --dry_run

      - name: Test new-module (help)
        run: |
          nix run .#new-module -- --help

      - name: Test setup-cachix (help)
        run: |
          nix run .#setup-cachix -- --help

      - name: Verify all POG apps are available
        run: |
          nix flake show | grep -A10 "apps" | grep -q "update-all" || exit 1
          nix flake show | grep -A10 "apps" | grep -q "new-module" || exit 1
          nix flake show | grep -A10 "apps" | grep -q "setup-cachix" || exit 1
          echo "✅ All POG apps are available"
